### ISSUE TITLE
cannot get any packets from the rpcx and client 

### ISSUE THREAD

**Issue by zhengchengbin610** [smallnest/rpcxdump#2]
![image](https://user-images.githubusercontent.com/26518131/62927767-ce703300-bde9-11e9-8021-f2ab2778ddf2.png)

the picture port 9808 is my rpcx listen port, but any log print , anyone can hellp me ?

**Comment by smallnest** [comment]
因为没有更详细的信息，可以从下面几个方面去debug:

1. rpcxdump监听的网卡和rpcx服务使用的网卡不是同一个网卡
2. rpcx服务没有调用

**Comment by smallnest** [comment]
不确定你的操作系统是否在windows。

我运行rpcx server和rpcx client在同一台windows中，不是127.0.0.1 loopbackip地址，是实际的ip地址，采用npcap进行packet捕获，结果捕获不到rpcx之间的通讯。

本地地址和外部地址之间的通讯可以捕获，但是我没有两台windows进行测试。所以目前可以说当rpcx服务和客户端在同一台windows上时是无法捕获的。

**Comment by smallnest** [comment]
貌似linux下也不能捕获了

**Comment by smallnest** [comment]
使用gopacket例子的捕获加强错误处理。Linux下可以捕获通讯
